### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by c93614** [bokuweb/zstd-wasm#104]
Dear @bokuweb 

I wanted to thank you for developing `@bokuweb/zstd-wasm` - it's a great library. I've been using `decompressUsingDict` to decompress data on the server-side and have found it to perform well during development.

However, while running benchmark testing on my service with `ab`, I encountered the following error: `RuntimeError: memory access out of bounds`.

```
RuntimeError: memory access out of bounds
    at wasm://wasm/00132a2e:wasm-function[172]:0x1260d
    at wasm://wasm/00132a2e:wasm-function[137]:0x856c
    at wasm://wasm/00132a2e:wasm-function[178]:0x175ca
    at wasm://wasm/00132a2e:wasm-function[248]:0x1f2d5
    at Object.decompress (/xxx/node_modules/.pnpm/@bokuweb+zstd-wasm@0.0.17/node_modules/@bokuweb/zstd-wasm/dist/common/simple/decompress.js:27:29)
    at Object.decompress (file:///xxx/build/lib/zstd.js:28:21)
    at decodeContent(file:///xxx/build/service/model.js:25:41)
    at Module.queryContent(file:///xxx/build/service/model.js:70:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I am running my service with NodeJS v16.19.1 and CentOS 7.9, Could you please help me understand the cause of this error and if there are any suggestions for quickly identifying the problem?

Thank you very much for your help!

**Comment by bokuweb** [comment]
@c93614 Thanks for reporting. Could you please provide a reproduced project?

**Comment by c93614** [comment]
Thank you for your quick response. To reproduce the error, please follow these steps:

1. Clone my testing repository: https://github.com/c93614/zstd-wasm-issue-104
2. Install the dependencies using `npm` or `pnpm`, then run `node index.js` to start the server for testing.
3. Open another terminal window and run `ab -c 10 -t 300 http://localhost:3030/decompress` to perform benchmark testing. You can adjust the `-c` (concurrency) and `-t` (time limit) options to try again later.
4. Please check if there are any error outputs in the terminal window that is running the server.

I encountered the following error message after approximately 43 seconds while performing the test on my M1 Mac:

~~~
Error: Failed to compress with code -70
    at Object.decompressUsingDict (/Users/c93614/devel/zstd-wasm-bug/node_modules/.pnpm/@bokuweb+zstd-wasm@0.0.17/node_modules/@bokuweb/zstd-wasm/dist/common/simple/decompress_using_dict.js:28:19)
    at /Users/c93614/devel/zstd-wasm-bug/index.js:39:41
    at dispatch (/Users/c93614/devel/zstd-wasm-bug/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/c93614/devel/zstd-wasm-bug/index.js:17:11
    at dispatch (/Users/c93614/devel/zstd-wasm-bug/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/c93614/devel/zstd-wasm-bug/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/Users/c93614/devel/zstd-wasm-bug/node_modules/.pnpm/koa@2.14.1/node_modules/koa/lib/application.js:182:12)
    at Server.handleRequest (/Users/c93614/devel/zstd-wasm-bug/node_modules/.pnpm/koa@2.14.1/node_modules/koa/lib/application.js:157:19)
    at Server.emit (node:events:520:28)
    at parserOnIncoming (node:_http_server:951:12)
~~~

And error message after about 52 seconds on a server with CeontOS 7.9:
~~~
RuntimeError: memory access out of bounds
    at wasm://wasm/00132a2e:wasm-function[172]:0x116f0
    at wasm://wasm/00132a2e:wasm-function[137]:0x856c
    at wasm://wasm/00132a2e:wasm-function[178]:0x175ca
    at wasm://wasm/00132a2e:wasm-function[250]:0x1f3e8
    at Object.createDCtx (/home/c93614/zstd-wasm-issue-104/node_modules/.pnpm/@bokuweb+zstd-wasm@0.0.17/node_modules/@bokuweb/zstd-wasm/dist/common/simple/decompress_using_dict.js:11:47)
    at /home/c93614/zstd-wasm-issue-104/index.js:39:66
    at dispatch (/home/c93614/zstd-wasm-issue-104/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /home/c93614/zstd-wasm-issue-104/index.js:17:11
    at dispatch (/home/c93614/zstd-wasm-issue-104/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /home/c93614/zstd-wasm-issue-104/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
~~~

Thank you for your help!

**Comment by c93614** [comment]
I have updated the testing repository to simplify the error reproduction process. Just clone it, install dependencies, and then run `node test.js`. After calling `decompressUsingDict` 8377 times, the error message appears:

~~~
/home/c93614/zstd-wasm-issue-104/node_modules/.pnpm/@bokuweb+zstd-wasm@0.0.17/node_modules/@bokuweb/zstd-wasm/dist/common/simple/decompress_using_dict.js:28
            throw new Error(`Failed to compress with code ${sizeOrError}`);
                  ^

Error: Failed to compress with code -70
    at Object.decompressUsingDict (/home/c93614/zstd-wasm-issue-104/node_modules/.pnpm/@bokuweb+zstd-wasm@0.0.17/node_modules/@bokuweb/zstd-wasm/dist/common/simple/decompress_using_dict.js:28:19)
    at /home/c93614/zstd-wasm-issue-104/test.js:20:41
~~~

**Comment by c93614** [comment]
Hi @bokuweb

I believe I may have identified the cause of the issue. It appears that in the [`decompress_using_dict.ts`](https://github.com/bokuweb/zstd-wasm/blob/master/lib/simple/decompress_using_dict.ts#L38) file, the pdict memory is not being freed. After adding the line `free(pdict, dict.byteLength);` at that point in the code, the script was able to loop more times before crashing (from 8377 to 22352), but it still eventually crashed.

One possible solution could be to expose the `ZSTD_freeDCtx` function to the wasm and call it in the JavaScript code. However, I'm currently experiencing difficulties in building the wasm module successfully.

**Comment by c93614** [comment]
I was able to resolve the issue with the changes made in this commit (https://github.com/c93614/zstd-wasm/commit/18d9e389aa9bede1521d1622cf8d938c54e2a074). However, I didn't update the documentation or the Deno-related scripts as they appear to be generated by `prettier`, and my `prettier` configuration may differ from yours.

I'm happy to create a pull request to merge the changes if you're interested in. Let me know if that's the case.

**Comment by bokuweb** [comment]
@c93614 Thanks fir your great work!!! could you please create a PR?

**Comment by c93614** [comment]
Thank you for merging this PR. I really appreciate your help and support!
